on:
  pull_request:
    branches:
      - main
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🚀 Create preview
        uses: expo/expo-github-action/preview@v8
        id: preview
        with:
          command: eas update --auto
          comment: false
        
      - name: Update pull request body
        uses: juztcode/pr-updater@1.0.0
        with:
          body: "![EXPO QR](${{ steps.preview.outputs.qr }})"
          token: ${{ secrets.GIT_TOKEN }}
